### ISSUE TITLE
Revo 2.2.5 conflicts 

### ISSUE THREAD

**Issue by sonicpunk** [lossendae/BigBrother#25]
After I upgraded my MODX to 2.2.5, the Big Brother tool does not work.  It can connect to my google analytics account, because it says connection successful.. but it does not show stats.  It keeps asking me to  select which Google Analytics profile that I want to use.  I select it and then the same screen keeps showing up asking for me to select an account.

**Comment by Mark-H** [comment]
There have been several fixes since this bug report related to selecting the profiles... @sonicpunk is it safe to assume this is no longer an issue? Or have you had it still?

**Comment by sonicpunk** [comment]
I have no longer noticed this issue.
