### ISSUE TITLE
Keeps prompting me to Select an account

### ISSUE THREAD

**Issue by jeremysanchez** [lossendae/BigBrother#30]
After authorization has been completed, I am prompted to "Select an account." However, once I select an account, the page refreshes and I am again asked to "Select an account." I am using Big Brother 1.1.0 rc2 on MODX 2.2.6. Reinstalling, clearing the cache, logging in/out...nothing seems to help.

**Comment by Mark-H** [comment]
Should no longer be an issue with 1.3.0
