### ISSUE TITLE
Wrong dates displayed on graph

### ISSUE THREAD

**Issue by rossng** [lossendae/BigBrother#33]
Here, the green line is marked as being 06 NOV 2013 - 06 DEC 2013. However, it's displaying data from 06 OCT 2013 - 06 NOV 2013.
![clipboard01](https://f.cloud.github.com/assets/565371/1698708/17ea51ea-5f5f-11e3-893d-d3058c4c8473.jpg)

**Comment by Mark-H** [comment]
https://github.com/modmore/BigBrother/issues/7
