### ISSUE TITLE
Blank 'Choose An Account' Dropdown

### ISSUE THREAD

**Issue by jivedog70** [lossendae/BigBrother#39]
At the 'Choose an Account' step I get a blank dropdown field. No ability to select the analytics account for this site (I manage multiple GA accounts).
![screenshot 2015-02-05 20 08 09](https://cloud.githubusercontent.com/assets/6612188/6074419/c32f5296-ad72-11e4-91b3-003b8004c793.png)

**Comment by DESIGNfromWITHIN** [comment]
Same issue here!

**Comment by Mark-H** [comment]
This should be fixed in 1.3.0-rc1.
