### ISSUE TITLE
Big Brother not working anymore

### ISSUE THREAD

**Issue by funkyduke** [lossendae/BigBrother#40]
Since a couple of days the plugin is not working anymore. I think Google must have chanced something to their API. I get following error (on all website where Big Brother is installed):
{"error":{"errors":[{"domain":"global","reason":"authError","message":"Invalid Credentials","locationType":"header","location":"Authorization"}],"code":401,"message":"Invalid Credentials"}}

**Comment by funkyduke** [comment]
https://support.google.com/a/answer/6201352

**Comment by gadgetto** [comment]
I don't think this add-on is actively maintained any longer... last change was 2 years ago. :-(

**Comment by sonicpunk** [comment]
It would be awesome if someone could pick up the project.  I am using this add-on on tons of websites... :(

**Comment by matdave** [comment]
Crud. Was hoping that wasn't the issue.

**Comment by hurby** [comment]
Same here, 
Maby Lossendea will make it work again, it would be great.

**Comment by mikelannen** [comment]
It would be really great to see this Extra working again. We used it on many sites and loved it!

**Comment by deyand** [comment]
Yeah, it will be great to see it working again.

**Comment by mikelannen** [comment]
I would make an online donation via PAYPAL if it will help speed things up? Maybe we could each donate $20 or something similar. I think we all find this Extra incredibly useful and would love to see it supported again. Anyone else down?

**Comment by hurby** [comment]
yes, count me in

Hurby

Op 18 mei 2015, om 16:26 heeft mikelannen het volgende geschreven:

> I would make an online donation via PAYPAL if it will help speed things up? Maybe we could each donate $20 or something similar. I think we all find this Extra incredibly useful and would love to see it supported again. Anyone else down?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Met vriendelijke groet
 WHP Kroon

 At Hurby's
 Plein Eendragt 25 b
 3111 AS Schiedam
 Mobile#              ++31 (0)626142194 
 Website              http://www.hurby..com

 Disclaimer   
 De informatie verzonden met dit e-mail bericht is vertrouwelijk en uitsluitend bestemd voor de 
 geadresseerde. Gebruik van deze informatie door anderen dan de geadresseerde is verboden. 
 Openbaarmaking, vermenigvuldiging, verspreiding en/of verstrekking van deze informatie aan derden is niet toegestaan. Indien u dit bericht foutief ontvangen hebt, wordt u gevraagd dit aan  afzender te melden en dit bericht te vernietigen.
 
 The information contained in this electronic mail message is privileged and confidential, and is  intended only for use of the addressee. If you are not the intended recipient, you are hereby notified that any disclosure, reproduction, distribution or other use of this communication is strictly prohibited. If you have received this communication in error, please notify the sender.

**Comment by sonicpunk** [comment]
I would also contribute financially to the project.

**Comment by mikelannen** [comment]
So what do we think lossendae? If we can get some contributions together, could we bring BigBrother back to life? Please? :-)

**Comment by gadgetto** [comment]
$30 Donation would be OK for me!

**Comment by lossendae** [comment]
Hi everyone, 
Thanks for the financing propositions but I unfortunately don't work with modx for the time being, and don't have the time necessary to update the package for now.
However, I'll asks some prominent community member if they want to take ownership on this package.

**Comment by hurby** [comment]
Okay,

Would be great if you can organize a modx member smart enough.
I would if i could but its beond my reach.

Hurby

Op 18 mei 2015, om 19:36 heeft lossendae het volgende geschreven:

> Hi everyone, 
> Thanks for the financing propositions but I unfortunately don't work with modx for the time being, and don't have the time necessary to update the package for now.
> However, I'll asks some prominent community member if they want to take ownership on this package.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Met vriendelijke groet
 WHP Kroon

 At Hurby's
 Plein Eendragt 25 b
 3111 AS Schiedam
 Mobile#              ++31 (0)626142194 
 Website              http://www.hurby..com

 Disclaimer   
 De informatie verzonden met dit e-mail bericht is vertrouwelijk en uitsluitend bestemd voor de 
 geadresseerde. Gebruik van deze informatie door anderen dan de geadresseerde is verboden. 
 Openbaarmaking, vermenigvuldiging, verspreiding en/of verstrekking van deze informatie aan derden is niet toegestaan. Indien u dit bericht foutief ontvangen hebt, wordt u gevraagd dit aan  afzender te melden en dit bericht te vernietigen.
 
 The information contained in this electronic mail message is privileged and confidential, and is  intended only for use of the addressee. If you are not the intended recipient, you are hereby notified that any disclosure, reproduction, distribution or other use of this communication is strictly prohibited. If you have received this communication in error, please notify the sender.

**Comment by Mark-H** [comment]
Anyone ever used BountySource? https://www.bountysource.com/issues/14554627-big-brother-not-working-anymore

If this was a relatively easy fix I would be more than happy to dive in and fix it as a community service (plus, I also have no more working analytics on my sites dashboards :o), but given I don't know any of the code, and I don't really know the ins and outs of this project, I'm a bit hesitant to make an actual commitment. I simply have no idea if it will take an hour or two weeks..

**Comment by Mark-H** [comment]
Okay, it looks like it does use the v3 API to load data, so that probably means it's just the authentication that needs to be rewritten... That might not be as bad as I may have thought..

**Comment by mikelannen** [comment]
Mark,

You would be a lifesaver if you can get this working and I would definitely
throw at least $20 bucks your way if you can get it working again. I am
sure many other would contribute as well. I miss my Big Brother!



Best Regards,


*MIKE LANNEN*
Founder + Creative Director
ETERNITY WEB <http://www.EternityMarketing.com>

(802) 865-2000  x700

*We've Moved!*


182 Main Street
Studio 3
Burlington, VT 05401

**Comment by hurby** [comment]
Mark,
That would be great!

MODX: Marks Online Developers eXtra's

regards
Hurby





Op 18 mei 2015, om 20:38 heeft Mark Hamstra het volgende geschreven:

> Okay, it looks like it does use the v3 API to load data, so that probably means it's just the authentication that needs to be rewritten... That might not be as bad as I may have thought..
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Met vriendelijke groet
 WHP Kroon

 At Hurby's
 Plein Eendragt 25 b
 3111 AS Schiedam
 Mobile#              ++31 (0)626142194 
 Website              http://www.hurby..com

 Disclaimer   
 De informatie verzonden met dit e-mail bericht is vertrouwelijk en uitsluitend bestemd voor de 
 geadresseerde. Gebruik van deze informatie door anderen dan de geadresseerde is verboden. 
 Openbaarmaking, vermenigvuldiging, verspreiding en/of verstrekking van deze informatie aan derden is niet toegestaan. Indien u dit bericht foutief ontvangen hebt, wordt u gevraagd dit aan  afzender te melden en dit bericht te vernietigen.
 
 The information contained in this electronic mail message is privileged and confidential, and is  intended only for use of the addressee. If you are not the intended recipient, you are hereby notified that any disclosure, reproduction, distribution or other use of this communication is strictly prohibited. If you have received this communication in error, please notify the sender.

**Comment by Mark-H** [comment]
Been making some progress, Google is now giving me an access and refresh token \o/

**Comment by hurby** [comment]
8-)

One down!

I've seen the error robot a 1000 times trying to do that.
You must be on the right track.

Hurby


Op 19 mei 2015, om 12:01 heeft Mark Hamstra het volgende geschreven:

> Been making some progress, Google is now giving me an access and refresh token \o/
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Met vriendelijke groet
 WHP Kroon

 At Hurby's
 Plein Eendragt 25 b
 3111 AS Schiedam
 Mobile#              ++31 (0)626142194 
 Website              http://www.hurby..com

 Disclaimer   
 De informatie verzonden met dit e-mail bericht is vertrouwelijk en uitsluitend bestemd voor de 
 geadresseerde. Gebruik van deze informatie door anderen dan de geadresseerde is verboden. 
 Openbaarmaking, vermenigvuldiging, verspreiding en/of verstrekking van deze informatie aan derden is niet toegestaan. Indien u dit bericht foutief ontvangen hebt, wordt u gevraagd dit aan  afzender te melden en dit bericht te vernietigen.
 
 The information contained in this electronic mail message is privileged and confidential, and is  intended only for use of the addressee. If you are not the intended recipient, you are hereby notified that any disclosure, reproduction, distribution or other use of this communication is strictly prohibited. If you have received this communication in error, please notify the sender.

**Comment by mikelannen** [comment]
Awesome!

On Tuesday, May 19, 2015, Mark Hamstra <notifications@github.com> wrote:

> Been making some progress, Google is now giving me an access and refresh
> token \o/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lossendae/BigBrother/issues/40#issuecomment-103423164>
> .
>


-- 



Best Regards,


*MIKE LANNEN*
Founder + Creative Director
ETERNITY WEB <http://www.EternityMarketing.com>

(802) 865-2000  x700

*We've Moved!*


182 Main Street
Studio 3
Burlington, VT 05401

**Comment by Mark-H** [comment]
![screen shot 2015-05-19 at 14 10 54](https://cloud.githubusercontent.com/assets/312944/7702513/ebf97e72-fe30-11e4-9df7-15c7fc02ba36.png)

Looks like it's almost there :)

**Comment by hurby** [comment]
Looks good !!





Op 19 mei 2015, om 14:11 heeft Mark Hamstra het volgende geschreven:

> 
> Looks like it's almost there :)
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Met vriendelijke groet
 WHP Kroon

 At Hurby's
 Plein Eendragt 25 b
 3111 AS Schiedam
 Mobile#              ++31 (0)626142194 
 Website              http://www.hurby..com

 Disclaimer   
 De informatie verzonden met dit e-mail bericht is vertrouwelijk en uitsluitend bestemd voor de 
 geadresseerde. Gebruik van deze informatie door anderen dan de geadresseerde is verboden. 
 Openbaarmaking, vermenigvuldiging, verspreiding en/of verstrekking van deze informatie aan derden is niet toegestaan. Indien u dit bericht foutief ontvangen hebt, wordt u gevraagd dit aan  afzender te melden en dit bericht te vernietigen.
 
 The information contained in this electronic mail message is privileged and confidential, and is  intended only for use of the addressee. If you are not the intended recipient, you are hereby notified that any disclosure, reproduction, distribution or other use of this communication is strictly prohibited. If you have received this communication in error, please notify the sender.

**Comment by mikelannen** [comment]
Mark, I could hug you my friend! I will definitely be donating after you have posted the new Extra!

**Comment by Mark-H** [comment]
I just pushed a 1.3 release, but it seems to **require everyone to set up an application in the google developer console** to work because the redirect_uri needs to be in a list of allowed uris. 

Maybe I missed something but I wont have time to look into it further until tomorrow.

**Comment by soulcreate** [comment]
Any instruction about "require everyone to set up an application in the google developer console"?

**Comment by soulcreate** [comment]
![image](https://cloud.githubusercontent.com/assets/2090261/7707056/d0616a96-fe6f-11e4-9d93-f30ee018231d.png)

**Comment by Mark-H** [comment]
https://console.developers.google.com/ - new project - APIs > credentials -
new web application > add your site as referral > copy the ID and secret
into the native_client_id/secret settings that's part of big brother 1.3.

I'll write up full instructions later if I can't figure out an easier way.
Op 19 mei 2015 5:41 PM schreef "Alexey Ch" <notifications@github.com>:

**Comment by JeffSokol** [comment]
I'm getting a few errors with the new release, Any ideas?

```
[19-May-2015 11:47:28] PHP Warning:  Unexpected character in input:  '\' (ASCII=92) state=1 in \core\components\bigbrother\model\bigbrother\bigbrother.class.php on line 114
[19-May-2015 11:47:28] PHP Parse error:  syntax error, unexpected T_STRING in \core\components\bigbrother\model\bigbrother\bigbrother.class.php on line 114
```

Thanks for taking this over Mark.

**Comment by gleighfield** [comment]
I'm gonna have to wait until an easier solution comes out - using big brother currently on (in excess of) 100 MODX installs... Dreading sorting this!

**Comment by Mark-H** [comment]
Yeah just give me some more time to sort it out, there has to be a better
way but I had to leave the office so just pushed what I had ;)
Op 19 mei 2015 8:18 PM schreef "Graeme Leighfield" <notifications@github.com

**Comment by Mark-H** [comment]
@JeffSokol: what version of PHP are you on? That error seems to indicate it is tripping over a namespace, which is a 5.3+ feature... you're not on 5.2 are you? :astonished:

**Comment by JeffSokol** [comment]
@Mark-H: I am indeed on 5.2.13. :sob:

**Comment by Mark-H** [comment]
Hi all! I just pushed 1.3.0-rc3 to modx.com, and you should be able of authenticating now without having to jump through hoops :tada: You'll be given a button to click, which will open a popup to the Google account selector/approval screen. That will give you a code to copy/paste back in to the MODX manager, which will then confirm your authentication and provide you a list of accounts.

Please let me know if you still have issues with getting authorized!

**Comment by Mark-H** [comment]
@JeffSokol: Sorry, but I'm not planning on fixing the issues on 5.2 - it has been unsupported by PHP itself for 4 years and counting: http://php.net/eol.php please (ask your host to) upgrade to at least 5.3.

**Comment by gleighfield** [comment]
Tried, tested and working :D


*Graeme Leighfield* - Director | GEL Studios Ltd
*Email* graeme@gelstudios.co.uk | *Phone *01793 238878 |* Mobile* 07774
976535

<http://www.facebook.com/gelstudios>  <https://twitter.com/gel_studios>
For support requests please email *support@gelstudios.co.uk
<support@gelstudios.co.uk>*

Please sponsor me for Tough Mudder South West 2015. Anything raised GEL
Studios will double! *Click here to donate!*
<https://www.eventbrite.com/donate/mucking-fudders-graeme-leighfield/1455411>

**Comment by sonicpunk** [comment]
So far so good, Mark!  Looks to be working

**Comment by jdaehne** [comment]
Hi Mark,
thanx a lot for that work. Works fine on the website i just tested updated. Please let me know wehre i can place my donation!

Jan

**Comment by Mark-H** [comment]
Awesome :) 

Donations are welcome via https://www.markhamstra.com/about/open-source/bigbrother/ If anyone needs an invoice with a donation, I can set up an invoice on modmore.com for that (which also has 6 other payment methods), just shoot me an email via hello@markhamstra.com in that case.

**Comment by hurby** [comment]
Mark,

I have donated 50 euro.
Thnx!!

Hurby

Op 20 mei 2015, om 13:26 heeft Mark Hamstra het volgende geschreven:

**Comment by gadgetto** [comment]
Euro 30,- donation placed!
Thanks a lot Mark!

Question: which is the official repository for BigBrother now, as I'd like to send some pull requests with cosmetical changes?

**Comment by deyand** [comment]
Brilliant job :-)
Thank you!

**Comment by gleighfield** [comment]
Donated 50 euro also :) Nice work mark

*Graeme Leighfield* - Director | GEL Studios Ltd
*Email* graeme@gelstudios.co.uk | *Phone *01793 238878 |* Mobile* 07774
976535

<http://www.facebook.com/gelstudios>  <https://twitter.com/gel_studios>
For support requests please email *support@gelstudios.co.uk
<support@gelstudios.co.uk>*

Please sponsor me for Tough Mudder South West 2015. Anything raised GEL
Studios will double! *Click here to donate!*
<https://www.eventbrite.com/donate/mucking-fudders-graeme-leighfield/1455411>

**Comment by sonicpunk** [comment]
I also gave 50 euro to Mr. Hamstra!

**Comment by Mark-H** [comment]
Wow, thanks guys! That's amazing and is really appreciated. 

@gadgetto for now, you should probably target https://github.com/modmore/BigBrother. I spoke with lossendae and there will probably be a message in the readme on this repo to go there.

**Comment by gadgetto** [comment]
Holy cow - now I needed to donate another Euro 20,- to draw level with other donators...  :-)

**Comment by lossendae** [comment]
Thank you Mark, I've updated the readme to redirect users to your repository.

**Comment by frischnetz** [comment]
Also left some euros … Thanks!

**Comment by JeffSokol** [comment]
no worries @Mark-H Thank you for doing what you have so far!

**Comment by Mark-H** [comment]
Thanks @lossendae! Also thanks for the donations guys, glad I could help.

**Comment by faitno** [comment]
CMP - work ok, but widget don't display any information...

**Comment by Mark-H** [comment]
@soulcreate do you get any errors when loading the widget? Either in the browser dev console or in the error log?

**Comment by hten** [comment]
Awesome thread.

**Comment by mikelannen** [comment]
Is anyone running in to an issue where when they initially load the dashboard in MODX that Bog Brother Google Analytics loads just white boxes until a hard refresh? I have noticed this on 6 different sites, in Chrome and FF (latest versions) on Mac.

**Comment by gleighfield** [comment]
Yes, i'm having the same...

_Graeme Leighfield_ - Director | GEL Studios Ltd
_Email_ graeme@gelstudios.co.uk | _Phone *01793 238878 |_ Mobile\* 07774
976535

http://www.facebook.com/gelstudios  https://twitter.com/gel_studios
For support requests please email _support@gelstudios.co.uk
support@gelstudios.co.uk_

Please sponsor me for Tough Mudder South West 2015. Anything raised GEL
Studios will double! _Click here to donate!_
https://www.eventbrite.com/donate/mucking-fudders-graeme-leighfield/1455411

**Comment by hten** [comment]
@mikelannen Yes, happened here.

**Comment by Mark-H** [comment]
I haven't personally seen that one yet, but let's open a new issue for that at https://github.com/modmore/BigBrother/issues

**Comment by mikelannen** [comment]
Done! Issue Created.

Best Regards,

_MIKE LANNEN_
Founder + Creative Director
ETERNITY WEB http://www.EternityMarketing.com

(802) 865-2000  x700

_We've Moved!_

182 Main Street
Studio 3
Burlington, VT 05401
