### ISSUE TITLE
Dashboard Blank Upon Initial Load - Works Upon Browser Refresh

### ISSUE THREAD

**Issue by mikelannen** [lossendae/BigBrother#43]
Dashboard Blank Boxes of Stats Upon Initial Load but then Works Upon Browser Refresh.

This is in REVO 2.33 on Chrome/FF (Latest) on Mac.

I have cleared all cache on MODX and in Browser and latest version of Big Brother installed and connected to GA accounts. This is happening on all sites that I have updated the Extra on.

It is only upon initial page load that it does not work.

**Comment by mikelannen** [comment]
Mark tripled the API requests for the Extra and from my side atleast this now appears to be resolved after I logged and and logged back in to the sites in question it now loads upon initial log in like it should.

**Comment by Mark-H** [comment]
https://github.com/modmore/BigBrother/issues/5
