### ISSUE TITLE
Feature Request: Additional Reporting Options

### ISSUE THREAD

**Issue by mikelannen** [lossendae/BigBrother#44]
Does anyone think there are additional reports that would be beneficial to show on the dashboard widget,  and within the view full report?

Maybe we could put a list together of what our clients would like to see most in there and vote on them and create a donation round for Mark to implement them if he has the time?

Thoughts?

**Comment by lossendae** [comment]
Hi Mike, the package owner has changed and is now located at https://github.com/modmore/BigBrother
You may ask for feature request directly on this new repository so I'm closing this issue.
